# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"plot_tree": "display.ipynb",
         "N": "go.ipynb",
         "MISSING_GROUP_ID": "go.ipynb",
         "ALL_COORDS": "go.ipynb",
         "EMPTY_BOARD": "go.ipynb",
         "NEIGHBORS": "go.ipynb",
         "DIAGONALS": "go.ipynb",
         "IllegalMove": "go.ipynb",
         "PlayerMove": "go.ipynb",
         "PositionWithContext": "go.ipynb",
         "place_stones": "go.ipynb",
         "replace_position": "go.ipynb",
         "find_reached": "go.ipynb",
         "is_koish": "go.ipynb",
         "is_eyeish": "go.ipynb",
         "Group": "go.ipynb",
         "LibertyTracker": "go.ipynb",
         "Position": "go.ipynb",
         "from_flat": "go.ipynb",
         "to_flat": "go.ipynb",
         "from_sgf": "go.ipynb",
         "to_sgf": "go.ipynb",
         "from_gtp": "go.ipynb",
         "to_gtp": "go.ipynb",
         "MCTSNode": "search.ipynb",
         "rng": "search.ipynb",
         "state_size": "search.ipynb",
         "n_actions": "search.ipynb",
         "n_sims": "search.ipynb",
         "root_idx": "search.ipynb",
         "tree": "search.ipynb"}

modules = ["display.py",
           "go.py",
           "search.py"]

doc_url = "https://WNoxchi.github.io/alphazero/"

git_url = "https://github.com/WNoxchi/alphazero/tree/master/"

def custom_doc_links(name): return None
