# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"plot_tree": "01_display.ipynb"}

modules = ["display.py"]

doc_url = "https://WNoxchi.github.io/alphazero/"

git_url = "https://github.com/WNoxchi/alphazero/tree/master/"

def custom_doc_links(name): return None
